Add `git fetch --all` to `spring-finalize-release.yml`
Sometimes commits may happen into a branch we are releasing against in between
build, deploy and this finalizer where we push release tag and two commits
for the released and next development versions

Observed a failure like this:
```
 ! [rejected]        3.3.x -> 3.3.x (fetch first)
error: failed to push some refs to 'https://github.com/spring-projects/spring-kafka'
hint: Updates were rejected because the remote contains work that you do not
hint: have locally. This is usually caused by another repository pushing to
hint: the same ref. If you want to integrate the remote changes, use
hint: 'git pull' before pushing again.
```